In [1]:
from newer_Galaxy import SpiralGalaxy

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

/home/sshamsi/miniconda3/envs/marvin/lib/python3.7/site-packages/marvin/core/exceptions.py:51: UserWarning: cannot initiate Sentry error reporting: [Errno 25] Inappropriate ioctl for device.
  UserWarning)


INFO: No release version set. Setting default to MPL-9



Bad key "text.kerning_factor" on line 4 in
/home/sshamsi/miniconda3/envs/marvin/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
/home/sshamsi/miniconda3/envs/marvin/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sshamsi/miniconda3/envs/marvin/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
path = '/home/sshamsi/sas/mangawork/manga/sandbox/galaxyzoo3d/v1_0_0/1-167242_127_5679242.fits.gz'
gal = SpiralGalaxy(path)

/home/sshamsi/miniconda3/envs/marvin/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sshamsi/miniconda3/envs/marvin/lib/python3.7/site-packages/marvin/utils/general/general.py:1086: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  value = np.asscalar(value)


In [3]:
centre_mask = gal.data.center_mask
star_mask = gal.data.star_mask
spiral_mask = gal.data.spiral_mask
bar_mask = gal.data.bar_mask

In [5]:
cv2.imwrite('gal_image.jpeg', gal.data.image, [cv2.IMWRITE_JPEG_QUALITY, 100])

True

In [6]:
image = cv2.imread('gal_image.jpeg')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2.imwrite('gal_image_grey.png', gray_image)

True

In [7]:
img_not = cv2.bitwise_not(gray_image)
cv2.imwrite('gal_image_greY_inv.png', img_not)

True

In [20]:
cv2.imwrite('mask.jpg', spiral_mask > 3)

TypeError: Expected Ptr<cv::UMat> for argument 'img'

In [23]:
mask_bounds = spiral_mask == 3

In [28]:
grey_baby = np.zeros((525, 525))

for i in range(525):
    for j in range(525):
        if mask_bounds[i, j]:
            grey_baby[i, j] = 0
        else:
            grey_baby[i, j] = gray_image[i, j]

In [30]:
cv2.imwrite("test.png", grey_baby)

True

In [31]:
grey_baby = np.zeros((525, 525))

for i in range(525):
    for j in range(525):
        if mask_bounds[i, j]:
            grey_baby[i, j] = 0
        else:
            grey_baby[i, j] = gray_image[i, j]

In [24]:
img_arrays = []

k = 100

while (k > 0):
    grey_baby = np.zeros((525, 525))
    
    for i in range(525):
        for j in range(525):
            if mask_bounds[i, j]:
                grey_baby[i, j] = img_not[i, j] - ((k/100) * img_not[i, j])
            else:
                grey_baby[i, j] = img_not[i, j]
    
    img_arrays.append(grey_baby)
    k = k - 1
    print(i, j, k)

524 524 99
524 524 98
524 524 97
524 524 96
524 524 95
524 524 94
524 524 93
524 524 92
524 524 91
524 524 90
524 524 89
524 524 88
524 524 87
524 524 86
524 524 85
524 524 84
524 524 83
524 524 82
524 524 81
524 524 80
524 524 79
524 524 78
524 524 77
524 524 76
524 524 75
524 524 74
524 524 73
524 524 72
524 524 71
524 524 70
524 524 69
524 524 68
524 524 67
524 524 66
524 524 65
524 524 64
524 524 63
524 524 62
524 524 61
524 524 60
524 524 59
524 524 58
524 524 57
524 524 56
524 524 55
524 524 54
524 524 53
524 524 52
524 524 51
524 524 50
524 524 49
524 524 48
524 524 47
524 524 46
524 524 45
524 524 44
524 524 43
524 524 42
524 524 41
524 524 40
524 524 39
524 524 38
524 524 37
524 524 36
524 524 35
524 524 34
524 524 33
524 524 32
524 524 31
524 524 30
524 524 29
524 524 28
524 524 27
524 524 26
524 524 25
524 524 24
524 524 23
524 524 22
524 524 21
524 524 20
524 524 19
524 524 18
524 524 17
524 524 16
524 524 15
524 524 14
524 524 13
524 524 12
524 524 11
524 524 10
524 524 9


In [25]:
img_arrays = np.array(img_arrays)

In [26]:
img_arrays.shape

(100, 525, 525)

In [27]:
j = 0

for img in img_arrays:
    cv2.imwrite('gif_images/' + str(j) + '.png', img)
    j += 1

In [62]:
import imageio

images = []
for i in range(100):
    images.append(imageio.imread('gif_images/' + str(i) + '.png'))
    
rev_imgs = images[1:][::-1]
images = images + rev_imgs

imageio.mimsave('movie.gif', images, duration=0.04)

In [52]:
frames[0].save('moving_ball.gif', format='GIF', append_images=frames[1:], save_all=True, fps=1)

In [50]:
len(frames)

100

In [59]:
lst = [1,2,3,5]

lst[::-1]

[5, 3, 2, 1]

In [20]:
l1 = np.array([[True, True, False, False],
               [False, False, True, True]])

l2 = np.array([[True, False, True, False],
               [False, True, False, True]])

In [21]:
l1

array([[ True,  True, False, False],
       [False, False,  True,  True]])

In [22]:
l2

array([[ True, False,  True, False],
       [False,  True, False,  True]])

In [23]:
l1 & l2

array([[ True, False, False, False],
       [False, False, False,  True]])

In [28]:
l3 = np.array([[3.44, 756, 8.98546, 75],
               [54.76, 74, 954.09, 75]])

In [29]:
l3 * l1

array([[  3.44, 756.  ,   0.  ,   0.  ],
       [  0.  ,   0.  , 954.09,  75.  ]])